# Generated by Django 3.2.8 on 2022-01-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220118_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ticket',
            field=models.FloatField(default=0),
        ),
    ]
