# Generated by Django 3.2.8 on 2022-01-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220118_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='beginDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='endDate',
            field=models.DateField(null=True),
        ),
    ]
